# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 09:40
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django_prices.models
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(max_length=200, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('hidden', models.BooleanField(default=False, verbose_name='hidden')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(max_length=200, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('hidden', models.BooleanField(default=False, verbose_name='hidden')),
                ('is_operational', models.BooleanField(default=False, verbose_name='is operational')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is featured')),
                ('is_open', models.BooleanField(default=False, verbose_name='is featured')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
            ],
            options={
                'ordering': ('-updated_at', 'position', 'name', 'location__point'),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'monday'), (2, 'tuesday'), (3, 'wednesday'), (4, 'thursday'), (5, 'friday'), (6, 'saturday'), (7, 'sunday')], unique=True)),
                ('from_hour', models.TimeField(verbose_name='open at')),
                ('to_hour', models.TimeField(verbose_name='close at')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='fsinfoservice.FuelStation')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('price', django_prices.models.PriceField(currency='USD', decimal_places=2, max_digits=12, verbose_name='price')),
                ('available_on', models.DateField(blank=True, null=True, verbose_name='available on')),
                ('is_available', models.BooleanField(default=True, verbose_name='is available')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is featured')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='fsinfoservice.Category', verbose_name='category')),
                ('fuel_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='fsinfoservice.FuelStation', verbose_name='fuel station')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fsinfoservice.Location'),
        ),
    ]
