# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsinfoservice', '0002_auto_20171124_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstation',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_station', to='fsinfoservice.Location'),
        ),
    ]
